global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - localhost:9093

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'zodiac-backend'
    static_configs:
      - targets: ['api.zodiaclifecoach.app:3000']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'zodiac-database'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']